# Generated by Django 5.0.3 on 2024-05-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymanagement', '0002_expensecategory_incomecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmexpense',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='farmexpense',
            old_name='expense_type',
            new_name='expense',
        ),
        migrations.RenameField(
            model_name='farmincome',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='farmincome',
            old_name='income_type',
            new_name='income',
        ),
        migrations.AddField(
            model_name='farmexpense',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moneymanagement.expensecategory'),
        ),
        migrations.AddField(
            model_name='farmexpense',
            name='user_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='farmincome',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moneymanagement.incomecategory'),
        ),
        migrations.AddField(
            model_name='farmincome',
            name='user_date',
            field=models.DateField(default=None),
        ),
    ]
